package Machine_Learnig_Program.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_FamilyValues extends EnumerationDescriptorBase {

  public EnumerationDescriptor_FamilyValues() {
    super(0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x6c2eeaf145e40d80L, "FamilyValues", "r:b37d5e84-f823-4791-a49e-0e8658d72e25(Machine_Learnig_Program.structure)/7795426327005498752");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_CLASSIFIER_0 = new EnumerationDescriptor.MemberDescriptor("CLASSIFIER", "CLASSIFIER", 0x6c2eeaf145e40d81L, "r:b37d5e84-f823-4791-a49e-0e8658d72e25(Machine_Learnig_Program.structure)/7795426327005498753");
  private final EnumerationDescriptor.MemberDescriptor myMember_REGRESSION_0 = new EnumerationDescriptor.MemberDescriptor("REGRESSION", "REGRESSION", 0x6c2eeaf145e40d82L, "r:b37d5e84-f823-4791-a49e-0e8658d72e25(Machine_Learnig_Program.structure)/7795426327005498754");
  private final EnumerationDescriptor.MemberDescriptor myMember_CLUSTERING_0 = new EnumerationDescriptor.MemberDescriptor("CLUSTERING", "CLUSTERING", 0x6c2eeaf145e40d85L, "r:b37d5e84-f823-4791-a49e-0e8658d72e25(Machine_Learnig_Program.structure)/7795426327005498757");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x6c2eeaf145e40d80L, 0x6c2eeaf145e40d81L, 0x6c2eeaf145e40d82L, 0x6c2eeaf145e40d85L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_CLASSIFIER_0, myMember_REGRESSION_0, myMember_CLUSTERING_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "CLASSIFIER":
        return myMember_CLASSIFIER_0;
      case "REGRESSION":
        return myMember_REGRESSION_0;
      case "CLUSTERING":
        return myMember_CLUSTERING_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
