package Machine_Learnig_Program.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_TypeValuesModel extends EnumerationDescriptorBase {

  public EnumerationDescriptor_TypeValuesModel() {
    super(0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x6c2eeaf145e40d89L, "TypeValuesModel", "r:b37d5e84-f823-4791-a49e-0e8658d72e25(Machine_Learnig_Program.structure)/7795426327005498761");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_ANN_0 = new EnumerationDescriptor.MemberDescriptor("ANN", "ANN", 0x6c2eeaf145e40d8aL, "r:b37d5e84-f823-4791-a49e-0e8658d72e25(Machine_Learnig_Program.structure)/7795426327005498762");
  private final EnumerationDescriptor.MemberDescriptor myMember_Tree_0 = new EnumerationDescriptor.MemberDescriptor("Tree", "Tree", 0x6c2eeaf145e40d8bL, "r:b37d5e84-f823-4791-a49e-0e8658d72e25(Machine_Learnig_Program.structure)/7795426327005498763");
  private final EnumerationDescriptor.MemberDescriptor myMember_RandomForrest_0 = new EnumerationDescriptor.MemberDescriptor("RandomForrest", "RandomForrest", 0x6c2eeaf145e40d8eL, "r:b37d5e84-f823-4791-a49e-0e8658d72e25(Machine_Learnig_Program.structure)/7795426327005498766");
  private final EnumerationDescriptor.MemberDescriptor myMember_SVM_0 = new EnumerationDescriptor.MemberDescriptor("SVM", "SVM", 0x6c2eeaf145e40d92L, "r:b37d5e84-f823-4791-a49e-0e8658d72e25(Machine_Learnig_Program.structure)/7795426327005498770");
  private final EnumerationDescriptor.MemberDescriptor myMember_DecisionTree_0 = new EnumerationDescriptor.MemberDescriptor("DecisionTree", "DecisionTree", 0x6c2eeaf145e40d97L, "r:b37d5e84-f823-4791-a49e-0e8658d72e25(Machine_Learnig_Program.structure)/7795426327005498775");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x6c2eeaf145e40d89L, 0x6c2eeaf145e40d8aL, 0x6c2eeaf145e40d8bL, 0x6c2eeaf145e40d8eL, 0x6c2eeaf145e40d92L, 0x6c2eeaf145e40d97L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_ANN_0, myMember_Tree_0, myMember_RandomForrest_0, myMember_SVM_0, myMember_DecisionTree_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "ANN":
        return myMember_ANN_0;
      case "Tree":
        return myMember_Tree_0;
      case "RandomForrest":
        return myMember_RandomForrest_0;
      case "SVM":
        return myMember_SVM_0;
      case "DecisionTree":
        return myMember_DecisionTree_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
