package Machine_Learnig_Program.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_TypeValues extends EnumerationDescriptorBase {

  public EnumerationDescriptor_TypeValues() {
    super(0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x6c2eeaf145e40d73L, "TypeValues", "r:b37d5e84-f823-4791-a49e-0e8658d72e25(Machine_Learnig_Program.structure)/7795426327005498739");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_NUMBER_0 = new EnumerationDescriptor.MemberDescriptor("NUMBER", "NUMBER", 0x6c2eeaf145e40d74L, "r:b37d5e84-f823-4791-a49e-0e8658d72e25(Machine_Learnig_Program.structure)/7795426327005498740");
  private final EnumerationDescriptor.MemberDescriptor myMember_CATEGORICAL_0 = new EnumerationDescriptor.MemberDescriptor("CATEGORICAL", "CATEGORICAL", 0x6c2eeaf145e40d79L, "r:b37d5e84-f823-4791-a49e-0e8658d72e25(Machine_Learnig_Program.structure)/7795426327005498745");
  private final EnumerationDescriptor.MemberDescriptor myMember_BINARY_0 = new EnumerationDescriptor.MemberDescriptor("BINARY", "BINARY", 0x6c2eeaf145e40d7cL, "r:b37d5e84-f823-4791-a49e-0e8658d72e25(Machine_Learnig_Program.structure)/7795426327005498748");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x6c2eeaf145e40d73L, 0x6c2eeaf145e40d74L, 0x6c2eeaf145e40d79L, 0x6c2eeaf145e40d7cL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_NUMBER_0, myMember_CATEGORICAL_0, myMember_BINARY_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "NUMBER":
        return myMember_NUMBER_0;
      case "CATEGORICAL":
        return myMember_CATEGORICAL_0;
      case "BINARY":
        return myMember_BINARY_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
