package Machine_Learnig_Program.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptButtonExport = createDescriptorForButtonExport();
  /*package*/ final ConceptDescriptor myConceptDescriptionModel = createDescriptorForDescriptionModel();
  /*package*/ final ConceptDescriptor myConceptFamilyModel = createDescriptorForFamilyModel();
  /*package*/ final ConceptDescriptor myConceptHead = createDescriptorForHead();
  /*package*/ final ConceptDescriptor myConceptInputBody = createDescriptorForInputBody();
  /*package*/ final ConceptDescriptor myConceptInputValue = createDescriptorForInputValue();
  /*package*/ final ConceptDescriptor myConceptInputsBody = createDescriptorForInputsBody();
  /*package*/ final ConceptDescriptor myConceptInputsStatement = createDescriptorForInputsStatement();
  /*package*/ final ConceptDescriptor myConceptLayerBody = createDescriptorForLayerBody();
  /*package*/ final ConceptDescriptor myConceptLayerValue = createDescriptorForLayerValue();
  /*package*/ final ConceptDescriptor myConceptLayersBody = createDescriptorForLayersBody();
  /*package*/ final ConceptDescriptor myConceptLayersStatement = createDescriptorForLayersStatement();
  /*package*/ final ConceptDescriptor myConceptMLDocument = createDescriptorForMLDocument();
  /*package*/ final ConceptDescriptor myConceptModelBody = createDescriptorForModelBody();
  /*package*/ final ConceptDescriptor myConceptModelStatement = createDescriptorForModelStatement();
  /*package*/ final ConceptDescriptor myConceptNameInput = createDescriptorForNameInput();
  /*package*/ final ConceptDescriptor myConceptNameLayer = createDescriptorForNameLayer();
  /*package*/ final ConceptDescriptor myConceptNameModel = createDescriptorForNameModel();
  /*package*/ final ConceptDescriptor myConceptNameOutput = createDescriptorForNameOutput();
  /*package*/ final ConceptDescriptor myConceptOutputBody = createDescriptorForOutputBody();
  /*package*/ final ConceptDescriptor myConceptOutputValue = createDescriptorForOutputValue();
  /*package*/ final ConceptDescriptor myConceptOutputsBody = createDescriptorForOutputsBody();
  /*package*/ final ConceptDescriptor myConceptOutputsStatement = createDescriptorForOutputsStatement();
  /*package*/ final ConceptDescriptor myConceptParams = createDescriptorForParams();
  /*package*/ final ConceptDescriptor myConceptParamsLayer = createDescriptorForParamsLayer();
  /*package*/ final ConceptDescriptor myConceptTypeInput = createDescriptorForTypeInput();
  /*package*/ final ConceptDescriptor myConceptTypeModel = createDescriptorForTypeModel();
  /*package*/ final ConceptDescriptor myConceptTypeOutput = createDescriptorForTypeOutput();
  /*package*/ final EnumerationDescriptor myEnumerationFamilyValues = new EnumerationDescriptor_FamilyValues();
  /*package*/ final EnumerationDescriptor myEnumerationTypeValues = new EnumerationDescriptor_TypeValues();
  /*package*/ final EnumerationDescriptor myEnumerationTypeValuesModel = new EnumerationDescriptor_TypeValuesModel();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptButtonExport, myConceptDescriptionModel, myConceptFamilyModel, myConceptHead, myConceptInputBody, myConceptInputValue, myConceptInputsBody, myConceptInputsStatement, myConceptLayerBody, myConceptLayerValue, myConceptLayersBody, myConceptLayersStatement, myConceptMLDocument, myConceptModelBody, myConceptModelStatement, myConceptNameInput, myConceptNameLayer, myConceptNameModel, myConceptNameOutput, myConceptOutputBody, myConceptOutputValue, myConceptOutputsBody, myConceptOutputsStatement, myConceptParams, myConceptParamsLayer, myConceptTypeInput, myConceptTypeModel, myConceptTypeOutput);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.ButtonExport:
        return myConceptButtonExport;
      case LanguageConceptSwitch.DescriptionModel:
        return myConceptDescriptionModel;
      case LanguageConceptSwitch.FamilyModel:
        return myConceptFamilyModel;
      case LanguageConceptSwitch.Head:
        return myConceptHead;
      case LanguageConceptSwitch.InputBody:
        return myConceptInputBody;
      case LanguageConceptSwitch.InputValue:
        return myConceptInputValue;
      case LanguageConceptSwitch.InputsBody:
        return myConceptInputsBody;
      case LanguageConceptSwitch.InputsStatement:
        return myConceptInputsStatement;
      case LanguageConceptSwitch.LayerBody:
        return myConceptLayerBody;
      case LanguageConceptSwitch.LayerValue:
        return myConceptLayerValue;
      case LanguageConceptSwitch.LayersBody:
        return myConceptLayersBody;
      case LanguageConceptSwitch.LayersStatement:
        return myConceptLayersStatement;
      case LanguageConceptSwitch.MLDocument:
        return myConceptMLDocument;
      case LanguageConceptSwitch.ModelBody:
        return myConceptModelBody;
      case LanguageConceptSwitch.ModelStatement:
        return myConceptModelStatement;
      case LanguageConceptSwitch.NameInput:
        return myConceptNameInput;
      case LanguageConceptSwitch.NameLayer:
        return myConceptNameLayer;
      case LanguageConceptSwitch.NameModel:
        return myConceptNameModel;
      case LanguageConceptSwitch.NameOutput:
        return myConceptNameOutput;
      case LanguageConceptSwitch.OutputBody:
        return myConceptOutputBody;
      case LanguageConceptSwitch.OutputValue:
        return myConceptOutputValue;
      case LanguageConceptSwitch.OutputsBody:
        return myConceptOutputsBody;
      case LanguageConceptSwitch.OutputsStatement:
        return myConceptOutputsStatement;
      case LanguageConceptSwitch.Params:
        return myConceptParams;
      case LanguageConceptSwitch.ParamsLayer:
        return myConceptParamsLayer;
      case LanguageConceptSwitch.TypeInput:
        return myConceptTypeInput;
      case LanguageConceptSwitch.TypeModel:
        return myConceptTypeModel;
      case LanguageConceptSwitch.TypeOutput:
        return myConceptTypeOutput;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationFamilyValues, myEnumerationTypeValues, myEnumerationTypeValuesModel);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForButtonExport() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Machine_Learnig_Program", "ButtonExport", 0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x16e61662a516fc48L);
    b.class_(false, false, false);
    b.origin("r:b37d5e84-f823-4791-a49e-0e8658d72e25(Machine_Learnig_Program.structure)/1650030926410218568");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDescriptionModel() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Machine_Learnig_Program", "DescriptionModel", 0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c38d4L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:b37d5e84-f823-4791-a49e-0e8658d72e25(Machine_Learnig_Program.structure)/3071300590990276820");
    b.version(3);
    b.property("Model_Description", 0x41e48fe65cd13ba5L).type(PrimitiveTypeId.STRING).origin("4748078126717811621").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFamilyModel() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Machine_Learnig_Program", "FamilyModel", 0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c38d2L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:b37d5e84-f823-4791-a49e-0e8658d72e25(Machine_Learnig_Program.structure)/3071300590990276818");
    b.version(3);
    b.property("Model_Family", 0x41e48fe65cd13b6aL).type(MetaIdFactory.dataTypeId(0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x6c2eeaf145e40d80L)).origin("4748078126717811562").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForHead() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Machine_Learnig_Program", "Head", 0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c36d0L);
    b.class_(false, false, false);
    b.origin("r:b37d5e84-f823-4791-a49e-0e8658d72e25(Machine_Learnig_Program.structure)/3071300590990276304");
    b.version(3);
    b.aggregate("Model_Name", 0x2a9f739d746e5685L).target(0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c38d1L).optional(true).ordered(true).multiple(false).origin("3071300590990415493").done();
    b.aggregate("Model_Family", 0x2a9f739d746e5689L).target(0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c38d2L).optional(true).ordered(true).multiple(false).origin("3071300590990415497").done();
    b.aggregate("Model_Type", 0x2a9f739d746e568cL).target(0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c38d3L).optional(true).ordered(true).multiple(false).origin("3071300590990415500").done();
    b.aggregate("Model_Description", 0x2a9f739d746e5690L).target(0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c38d4L).optional(true).ordered(true).multiple(false).origin("3071300590990415504").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInputBody() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Machine_Learnig_Program", "InputBody", 0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c38d8L);
    b.class_(false, false, false);
    b.origin("r:b37d5e84-f823-4791-a49e-0e8658d72e25(Machine_Learnig_Program.structure)/3071300590990276824");
    b.version(3);
    b.aggregate("Name_Input", 0x6c2eeaf145ce9c45L).target(0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c38d9L).optional(false).ordered(true).multiple(false).origin("7795426327004093509").done();
    b.aggregate("Type_Input", 0x6c2eeaf145ce9c47L).target(0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c38daL).optional(true).ordered(true).multiple(false).origin("7795426327004093511").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInputValue() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Machine_Learnig_Program", "InputValue", 0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c38d7L);
    b.class_(false, false, false);
    b.origin("r:b37d5e84-f823-4791-a49e-0e8658d72e25(Machine_Learnig_Program.structure)/3071300590990276823");
    b.version(3);
    b.aggregate("InputBody", 0x6c2eeaf145ce5403L).target(0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c38d8L).optional(true).ordered(true).multiple(false).origin("7795426327004075011").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInputsBody() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Machine_Learnig_Program", "InputsBody", 0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c38d6L);
    b.class_(false, false, false);
    b.origin("r:b37d5e84-f823-4791-a49e-0e8658d72e25(Machine_Learnig_Program.structure)/3071300590990276822");
    b.version(3);
    b.aggregate("InputValue", 0x6c2eeaf145ce0deaL).target(0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c38d7L).optional(false).ordered(true).multiple(true).origin("7795426327004057066").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInputsStatement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Machine_Learnig_Program", "InputsStatement", 0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c38d5L);
    b.class_(false, false, false);
    b.origin("r:b37d5e84-f823-4791-a49e-0e8658d72e25(Machine_Learnig_Program.structure)/3071300590990276821");
    b.version(3);
    b.aggregate("InputsBody", 0x2a9f739d746fb287L).target(0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c38d6L).optional(true).ordered(true).multiple(false).origin("3071300590990504583").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLayerBody() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Machine_Learnig_Program", "LayerBody", 0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c3900L);
    b.class_(false, false, false);
    b.origin("r:b37d5e84-f823-4791-a49e-0e8658d72e25(Machine_Learnig_Program.structure)/3071300590990276864");
    b.version(3);
    b.aggregate("NameLayer", 0x6c2eeaf145d4f4b3L).target(0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c3901L).optional(false).ordered(true).multiple(false).origin("7795426327004509363").done();
    b.aggregate("ParamsLayer", 0x6c2eeaf145d4f4b5L).target(0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c3902L).optional(false).ordered(true).multiple(false).origin("7795426327004509365").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLayerValue() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Machine_Learnig_Program", "LayerValue", 0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c38ffL);
    b.class_(false, false, false);
    b.origin("r:b37d5e84-f823-4791-a49e-0e8658d72e25(Machine_Learnig_Program.structure)/3071300590990276863");
    b.version(3);
    b.aggregate("LayerBody", 0x6c2eeaf145d2ee92L).target(0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c3900L).optional(true).ordered(true).multiple(false).origin("7795426327004376722").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLayersBody() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Machine_Learnig_Program", "LayersBody", 0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c38feL);
    b.class_(false, false, false);
    b.origin("r:b37d5e84-f823-4791-a49e-0e8658d72e25(Machine_Learnig_Program.structure)/3071300590990276862");
    b.version(3);
    b.aggregate("LayerValue", 0x6c2eeaf145d2ee7bL).target(0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c38ffL).optional(false).ordered(true).multiple(true).origin("7795426327004376699").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLayersStatement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Machine_Learnig_Program", "LayersStatement", 0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c38e3L);
    b.class_(false, false, false);
    b.origin("r:b37d5e84-f823-4791-a49e-0e8658d72e25(Machine_Learnig_Program.structure)/3071300590990276835");
    b.version(3);
    b.aggregate("LayersBody", 0x6c2eeaf145d2ee1aL).target(0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c38feL).optional(true).ordered(true).multiple(true).origin("7795426327004376602").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMLDocument() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Machine_Learnig_Program", "MLDocument", 0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746aa77eL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:b37d5e84-f823-4791-a49e-0e8658d72e25(Machine_Learnig_Program.structure)/3071300590990174078");
    b.version(3);
    b.aggregate("Head", 0x2a9f739d746ec00eL).target(0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c36d0L).optional(true).ordered(true).multiple(false).origin("3071300590990442510").done();
    b.aggregate("InputsStatement", 0x6c2eeaf145ccc927L).target(0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c38d5L).optional(true).ordered(true).multiple(false).origin("7795426327003973927").done();
    b.aggregate("OutputsStatement", 0x6c2eeaf145ccca59L).target(0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c38dbL).optional(true).ordered(true).multiple(false).origin("7795426327003974233").done();
    b.aggregate("ModelStatement", 0x6c2eeaf145ccca5dL).target(0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c38e1L).optional(true).ordered(true).multiple(false).origin("7795426327003974237").done();
    b.alias("MLDocument");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForModelBody() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Machine_Learnig_Program", "ModelBody", 0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c38e2L);
    b.class_(false, false, false);
    b.origin("r:b37d5e84-f823-4791-a49e-0e8658d72e25(Machine_Learnig_Program.structure)/3071300590990276834");
    b.version(3);
    b.aggregate("LayersStatement", 0x6c2eeaf145d2edf2L).target(0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c38e3L).optional(false).ordered(true).multiple(true).origin("7795426327004376562").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForModelStatement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Machine_Learnig_Program", "ModelStatement", 0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c38e1L);
    b.class_(false, false, false);
    b.origin("r:b37d5e84-f823-4791-a49e-0e8658d72e25(Machine_Learnig_Program.structure)/3071300590990276833");
    b.version(3);
    b.aggregate("Model_Body", 0x6c2eeaf145d2edd8L).target(0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c38e2L).optional(true).ordered(true).multiple(false).origin("7795426327004376536").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForNameInput() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Machine_Learnig_Program", "NameInput", 0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c38d9L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:b37d5e84-f823-4791-a49e-0e8658d72e25(Machine_Learnig_Program.structure)/3071300590990276825");
    b.version(3);
    b.property("Input_Name", 0x6c2eeaf145ceea71L).type(PrimitiveTypeId.STRING).origin("7795426327004113521").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForNameLayer() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Machine_Learnig_Program", "NameLayer", 0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c3901L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:b37d5e84-f823-4791-a49e-0e8658d72e25(Machine_Learnig_Program.structure)/3071300590990276865");
    b.version(3);
    b.property("NameLayer", 0x6c2eeaf145dde9deL).type(PrimitiveTypeId.STRING).origin("7795426327005096414").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForNameModel() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Machine_Learnig_Program", "NameModel", 0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c38d1L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:b37d5e84-f823-4791-a49e-0e8658d72e25(Machine_Learnig_Program.structure)/3071300590990276817");
    b.version(3);
    b.property("Model_Name", 0x41e48fe65cd13b12L).type(PrimitiveTypeId.STRING).origin("4748078126717811474").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForNameOutput() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Machine_Learnig_Program", "NameOutput", 0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c38dfL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:b37d5e84-f823-4791-a49e-0e8658d72e25(Machine_Learnig_Program.structure)/3071300590990276831");
    b.version(3);
    b.property("Output_Name", 0x6c2eeaf145ceea75L).type(PrimitiveTypeId.STRING).origin("7795426327004113525").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForOutputBody() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Machine_Learnig_Program", "OutputBody", 0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c38deL);
    b.class_(false, false, false);
    b.origin("r:b37d5e84-f823-4791-a49e-0e8658d72e25(Machine_Learnig_Program.structure)/3071300590990276830");
    b.version(3);
    b.aggregate("NameOutput", 0x6c2eeaf145ceea19L).target(0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c38dfL).optional(false).ordered(true).multiple(false).origin("7795426327004113433").done();
    b.aggregate("TypeOutput", 0x6c2eeaf145ceea1bL).target(0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c38e0L).optional(true).ordered(true).multiple(false).origin("7795426327004113435").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForOutputValue() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Machine_Learnig_Program", "OutputValue", 0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c38ddL);
    b.class_(false, false, false);
    b.origin("r:b37d5e84-f823-4791-a49e-0e8658d72e25(Machine_Learnig_Program.structure)/3071300590990276829");
    b.version(3);
    b.aggregate("OutputBody", 0x6c2eeaf145cee9edL).target(0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c38deL).optional(true).ordered(true).multiple(false).origin("7795426327004113389").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForOutputsBody() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Machine_Learnig_Program", "OutputsBody", 0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c38dcL);
    b.class_(false, false, false);
    b.origin("r:b37d5e84-f823-4791-a49e-0e8658d72e25(Machine_Learnig_Program.structure)/3071300590990276828");
    b.version(3);
    b.aggregate("OutputValue", 0x6c2eeaf145cee9d6L).target(0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c38ddL).optional(false).ordered(true).multiple(true).origin("7795426327004113366").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForOutputsStatement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Machine_Learnig_Program", "OutputsStatement", 0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c38dbL);
    b.class_(false, false, false);
    b.origin("r:b37d5e84-f823-4791-a49e-0e8658d72e25(Machine_Learnig_Program.structure)/3071300590990276827");
    b.version(3);
    b.aggregate("OutputsBody", 0x6c2eeaf145cee9bcL).target(0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c38dcL).optional(true).ordered(true).multiple(false).origin("7795426327004113340").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForParams() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Machine_Learnig_Program", "Params", 0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c3903L);
    b.class_(false, false, false);
    b.origin("r:b37d5e84-f823-4791-a49e-0e8658d72e25(Machine_Learnig_Program.structure)/3071300590990276867");
    b.version(3);
    b.property("Number", 0x6c2eeaf145d8861aL).type(PrimitiveTypeId.INTEGER).origin("7795426327004743194").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForParamsLayer() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Machine_Learnig_Program", "ParamsLayer", 0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c3902L);
    b.class_(false, false, false);
    b.origin("r:b37d5e84-f823-4791-a49e-0e8658d72e25(Machine_Learnig_Program.structure)/3071300590990276866");
    b.version(3);
    b.aggregate("Params", 0x6c2eeaf145d885d8L).target(0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c3903L).optional(true).ordered(true).multiple(true).origin("7795426327004743128").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTypeInput() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Machine_Learnig_Program", "TypeInput", 0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c38daL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:b37d5e84-f823-4791-a49e-0e8658d72e25(Machine_Learnig_Program.structure)/3071300590990276826");
    b.version(3);
    b.property("Input_Type", 0x6c2eeaf145ceea73L).type(MetaIdFactory.dataTypeId(0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x6c2eeaf145e40d73L)).origin("7795426327004113523").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTypeModel() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Machine_Learnig_Program", "TypeModel", 0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c38d3L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:b37d5e84-f823-4791-a49e-0e8658d72e25(Machine_Learnig_Program.structure)/3071300590990276819");
    b.version(3);
    b.property("Model_Type", 0x41e48fe65cd13b89L).type(MetaIdFactory.dataTypeId(0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x6c2eeaf145e40d89L)).origin("4748078126717811593").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTypeOutput() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Machine_Learnig_Program", "TypeOutput", 0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x2a9f739d746c38e0L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:b37d5e84-f823-4791-a49e-0e8658d72e25(Machine_Learnig_Program.structure)/3071300590990276832");
    b.version(3);
    b.property("Output_Type", 0x6c2eeaf145ceea7bL).type(MetaIdFactory.dataTypeId(0xf03daa50cd2c41b9L, 0x926581a1c1e4c00cL, 0x6c2eeaf145e40d80L)).origin("7795426327004113531").done();
    return b.create();
  }
}
